"use client";
import {useMemo,useState} from "react";

type Creator={handle:string;platform:string;category:string;score:number;fit:number;auth:number;eng:number};
type Roi={conversions:number;revenue:number;cost:number;profit:number;roas:number;roi:number};
type Campaign={id:string;name:string;objective:string;period:string;budget:number;accent:string;creators:Creator[];roi:Record<string,Roi>;compliance:[number,number,number]};

const data:Campaign[]=[
 {id:"CAM-001",name:"EcoGlow Summer Launch",objective:"Awareness",period:"01–30 Sep 2026",budget:500000,accent:"#6747ee",compliance:[1,0,2],creators:[
  {handle:"creator_19",platform:"Instagram",category:"Beauty",score:66.67,fit:43,auth:95,eng:85},{handle:"creator_07",platform:"Instagram",category:"Beauty",score:64.42,fit:43,auth:100,eng:75},{handle:"creator_13",platform:"Instagram",category:"Beauty",score:60.92,fit:43,auth:100,eng:65},{handle:"creator_25",platform:"Instagram",category:"Beauty",score:56.42,fit:43,auth:90,eng:45},{handle:"creator_28",platform:"Instagram",category:"Food",score:56.25,fit:15,auth:100,eng:95}],roi:{conservative:{conversions:168,revenue:302400,cost:375000,profit:-178440,roas:.81,roi:-47.58},expected:{conversions:350,revenue:630000,cost:375000,profit:34500,roas:1.68,roi:9.2},optimistic:{conversions:604,revenue:1086750,cost:375000,profit:331388,roas:2.9,roi:88.37}}},
 {id:"CAM-002",name:"PulseFit Challenge",objective:"Conversions",period:"01–31 Oct 2026",budget:750000,accent:"#ef5da8",compliance:[1,1,0],creators:[
  {handle:"creator_02",platform:"YouTube",category:"Fitness",score:87.5,fit:83,auth:95,eng:85},{handle:"creator_26",platform:"YouTube",category:"Fitness",score:80.5,fit:83,auth:95,eng:65},{handle:"creator_14",platform:"YouTube",category:"Fitness",score:76.75,fit:83,auth:100,eng:45},{handle:"creator_08",platform:"YouTube",category:"Fitness",score:70.5,fit:83,auth:83,eng:25},{handle:"creator_28",platform:"Instagram",category:"Food",score:56.25,fit:15,auth:100,eng:95}],roi:{conservative:{conversions:230,revenue:690970,cost:560000,profit:-41773,roas:1.23,roi:-7.46},expected:{conversions:480,revenue:1439520,cost:560000,profit:519640,roas:2.57,roi:92.79},optimistic:{conversions:828,revenue:2483172,cost:560000,profit:1302379,roas:4.43,roi:232.57}}},
 {id:"CAM-003",name:"WanderLite Weekends",objective:"Traffic",period:"01–30 Nov 2026",budget:600000,accent:"#f39b39",compliance:[0,1,1],creators:[
  {handle:"creator_21",platform:"TikTok",category:"Travel",score:75.81,fit:68,auth:100,eng:75},{handle:"creator_27",platform:"TikTok",category:"Travel",score:72.56,fit:53,auth:95,eng:85},{handle:"creator_03",platform:"TikTok",category:"Travel",score:70.56,fit:68,auth:95,eng:35},{handle:"creator_09",platform:"TikTok",category:"Travel",score:66.31,fit:53,auth:100,eng:55},{handle:"creator_15",platform:"TikTok",category:"Travel",score:64.06,fit:68,auth:95,eng:25}],roi:{conservative:{conversions:73,revenue:907200,cost:530000,profit:-330416,roas:1.71,roi:-62.34},expected:{conversions:151,revenue:1890000,cost:530000,profit:-114200,roas:3.57,roi:-21.55},optimistic:{conversions:261,revenue:3260250,cost:530000,profit:187255,roas:6.15,roi:35.33}}}
];
const cash=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);
const short=(n:number)=>`${n<0?"-":""}₹${(Math.abs(n)/100000).toFixed(1)}L`;
const icons:Record<string,string>={overview:"M3 3h7v7H3zM14 3h7v4h-7zM14 11h7v10h-7zM3 14h7v7H3z",people:"M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8",shield:"M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10M9 12l2 2 4-4",chart:"M3 20h18M6 16l4-5 4 3 5-8"};
function Icon({name}:{name:string}){return <svg viewBox="0 0 24 24"><path d={icons[name]}/></svg>}

export default function Home(){
 const [id,setId]=useState("CAM-002"),[scenario,setScenario]=useState("expected");
 const campaign=useMemo(()=>data.find(x=>x.id===id)!,[id]),roi=campaign.roi[scenario],checks=campaign.compliance.reduce((a,b)=>a+b,0);
 return <div className="shell"><aside><div className="brand"><b>IT</b><span>Influencer<em>Trust</em></span></div><nav><a className="active"><Icon name="overview"/>Overview</a><a><Icon name="people"/>Creators</a><a><Icon name="shield"/>Authenticity</a><a><Icon name="chart"/>ROI simulator</a></nav><div className="status"><small>MODEL STATUS</small><strong><i/>Analysis ready</strong><span>Last refreshed today</span></div></aside>
 <main><header><div><small>CAMPAIGN INTELLIGENCE</small><h1>Performance overview</h1><p>Rank creators, screen risk and forecast returns in one place.</p></div><div><button>Export report</button><b>KM</b></div></header>
 <section className="campaign"><div className="current"><i style={{background:campaign.accent}}/><span><small>ACTIVE CAMPAIGN</small><b>{campaign.name}</b></span></div><div className="meta"><span><small>OBJECTIVE</small>{campaign.objective}</span><span><small>RUN DATES</small>{campaign.period}</span><span><small>BUDGET</small>{cash(campaign.budget)}</span></div><select aria-label="Choose campaign" value={id} onChange={e=>setId(e.target.value)}>{data.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></section>
 <section className="kpis"><Kpi label="Top creator score" value={campaign.creators[0].score.toFixed(1)} note={`@${campaign.creators[0].handle} leads`} badge="Low risk"/><Kpi label="Expected ROI" value={`${campaign.roi.expected.roi.toFixed(1)}%`} note={`${campaign.roi.expected.roas.toFixed(2)}× ROAS`} badge={campaign.roi.expected.roi>=0?"Profitable":"At risk"} bad={campaign.roi.expected.roi<0}/><Kpi label="Compliance health" value={`${Math.round(campaign.compliance[0]/checks*100)}%`} note={`${campaign.compliance[1]+campaign.compliance[2]} item(s) need attention`} badge={`${checks} checks`}/></section>
 <section className="content"><article className="panel ranking"><div className="panel-head"><span><h2>Recommended creators</h2><p>Explainable ranking for campaign fit and quality</p></span><button>View all →</button></div><div className="table"><table><thead><tr><th>RANK</th><th>CREATOR</th><th>OVERALL</th><th>FIT</th><th>AUTHENTICITY</th><th>ENGAGEMENT</th></tr></thead><tbody>{campaign.creators.map((c,i)=><tr key={c.handle}><td><b className={i===0?"rank first":"rank"}>{i+1}</b></td><td><div className="creator"><i>{c.handle.slice(-2)}</i><span><b>@{c.handle}</b><small>{c.platform} · {c.category}</small></span></div></td><td><b>{c.score.toFixed(1)}</b></td><td><Score n={c.fit}/></td><td><Score n={c.auth}/></td><td><Score n={c.eng}/></td></tr>)}</tbody></table></div></article>
 <article className="panel forecast"><div className="panel-head"><span><h2>ROI forecast</h2><p>Scenario-based contribution return</p></span></div><div className="tabs">{["conservative","expected","optimistic"].map(x=><button className={x===scenario?"on":""} onClick={()=>setScenario(x)} key={x}>{x}</button>)}</div><div className="profit"><small>{scenario} contribution</small><strong className={roi.profit<0?"negative":""}>{short(roi.profit)}</strong><em className={roi.roi<0?"negative":""}>{roi.roi>=0?"+":""}{roi.roi.toFixed(1)}% ROI</em></div><div className="bars"><Bar label="Revenue" n={roi.revenue} h={Math.min(100,roi.revenue/33000)}/><Bar label="Cost" n={roi.cost} h={Math.min(100,roi.cost/8000)} kind="cost"/><Bar label="Contribution" n={roi.profit} h={Math.max(12,Math.min(100,Math.abs(roi.profit)/14000))} kind={roi.profit<0?"loss":"gain"}/></div><div className="mini"><span>Conversions<b>{Math.round(roi.conversions)}</b></span><span>ROAS<b>{roi.roas.toFixed(2)}×</b></span></div></article></section>
 <footer><span>Scores support decisions; they do not guarantee outcomes.</span><b>InfluencerTrust AI · MVP v1.0</b></footer></main></div>
}
function Kpi({label,value,note,badge,bad=false}:{label:string,value:string,note:string,badge:string,bad?:boolean}){return <article><div><span>{label}</span><em>{badge}</em></div><strong className={bad?"negative":""}>{value}</strong><p>{note}</p><i className="accent"/></article>}
function Score({n}:{n:number}){return <div className="score"><span><i style={{width:`${n}%`}}/></span><small>{n}</small></div>}
function Bar({label,n,h,kind=""}:{label:string,n:number,h:number,kind?:string}){return <div><i className={kind} style={{height:`${h}%`}}/><small>{label}</small><b>{short(n)}</b></div>}
