"use client";
import {useMemo,useState} from "react";

type Creator={handle:string;platform:string;category:string;score:number;fit:number;auth:number;eng:number};
type Roi={conversions:number;revenue:number;cost:number;profit:number;roas:number;roi:number};
type Campaign={id:string;name:string;objective:string;period:string;budget:number;accent:string;creators:Creator[];roi:Record<string,Roi>;compliance:[number,number,number]};
type ComplianceResult={id:string;campaignId:string;score:number;status:"compliant"|"review"|"blocked";missing:string[];prohibited:string[];suggestion:string};
type SavedProject={id:string;name:string;updatedAt:string;payload:{campaigns:Campaign[];id:string;scenario:string;complianceResults:ComplianceResult[];brief:string[]}};
type YouTubeResult={source:string;fetchedAt:string;channel:{id:string;title:string;subscribers:number;videoCount:number;totalViews:number};metrics:{sampleSize:number;avgViews:number;avgLikes:number;avgComments:number;engagementRatePct:number}};

const data:Campaign[]=[
 {id:"CAM-001",name:"EcoGlow Summer Launch",objective:"Awareness",period:"01–30 Sep 2026",budget:500000,accent:"#6747ee",compliance:[1,0,2],creators:[
  {handle:"creator_19",platform:"Instagram",category:"Beauty",score:66.67,fit:43,auth:95,eng:85},{handle:"creator_07",platform:"Instagram",category:"Beauty",score:64.42,fit:43,auth:100,eng:75},{handle:"creator_13",platform:"Instagram",category:"Beauty",score:60.92,fit:43,auth:100,eng:65},{handle:"creator_25",platform:"Instagram",category:"Beauty",score:56.42,fit:43,auth:90,eng:45},{handle:"creator_28",platform:"Instagram",category:"Food",score:56.25,fit:15,auth:100,eng:95}],roi:{conservative:{conversions:168,revenue:302400,cost:375000,profit:-178440,roas:.81,roi:-47.58},expected:{conversions:350,revenue:630000,cost:375000,profit:34500,roas:1.68,roi:9.2},optimistic:{conversions:604,revenue:1086750,cost:375000,profit:331388,roas:2.9,roi:88.37}}},
 {id:"CAM-002",name:"PulseFit Challenge",objective:"Conversions",period:"01–31 Oct 2026",budget:750000,accent:"#ef5da8",compliance:[1,1,0],creators:[
  {handle:"creator_02",platform:"YouTube",category:"Fitness",score:87.5,fit:83,auth:95,eng:85},{handle:"creator_26",platform:"YouTube",category:"Fitness",score:80.5,fit:83,auth:95,eng:65},{handle:"creator_14",platform:"YouTube",category:"Fitness",score:76.75,fit:83,auth:100,eng:45},{handle:"creator_08",platform:"YouTube",category:"Fitness",score:70.5,fit:83,auth:83,eng:25},{handle:"creator_28",platform:"Instagram",category:"Food",score:56.25,fit:15,auth:100,eng:95}],roi:{conservative:{conversions:230,revenue:690970,cost:560000,profit:-41773,roas:1.23,roi:-7.46},expected:{conversions:480,revenue:1439520,cost:560000,profit:519640,roas:2.57,roi:92.79},optimistic:{conversions:828,revenue:2483172,cost:560000,profit:1302379,roas:4.43,roi:232.57}}},
 {id:"CAM-003",name:"WanderLite Weekends",objective:"Traffic",period:"01–30 Nov 2026",budget:600000,accent:"#f39b39",compliance:[0,1,1],creators:[
  {handle:"creator_21",platform:"TikTok",category:"Travel",score:75.81,fit:68,auth:100,eng:75},{handle:"creator_27",platform:"TikTok",category:"Travel",score:72.56,fit:53,auth:95,eng:85},{handle:"creator_03",platform:"TikTok",category:"Travel",score:70.56,fit:68,auth:95,eng:35},{handle:"creator_09",platform:"TikTok",category:"Travel",score:66.31,fit:53,auth:100,eng:55},{handle:"creator_15",platform:"TikTok",category:"Travel",score:64.06,fit:68,auth:95,eng:25}],roi:{conservative:{conversions:73,revenue:907200,cost:530000,profit:-330416,roas:1.71,roi:-62.34},expected:{conversions:151,revenue:1890000,cost:530000,profit:-114200,roas:3.57,roi:-21.55},optimistic:{conversions:261,revenue:3260250,cost:530000,profit:187255,roas:6.15,roi:35.33}}}
];
const cash=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);
const short=(n:number)=>`${n<0?"-":""}₹${(Math.abs(n)/100000).toFixed(1)}L`;
function parseCsv(text:string){
 const rows:string[][]=[];let row:string[]=[],cell="",quoted=false;
 for(let i=0;i<text.length;i++){const ch=text[i],next=text[i+1];if(ch==='"'&&quoted&&next==='"'){cell+='"';i++;}else if(ch==='"')quoted=!quoted;else if(ch===','&&!quoted){row.push(cell);cell="";}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&next==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell="";}else cell+=ch;}
 row.push(cell);if(row.some(Boolean))rows.push(row);const headers=rows.shift()?.map(x=>x.trim())??[];
 return rows.map(values=>Object.fromEntries(headers.map((h,i)=>[h,(values[i]??"").trim()])));
}
const clamp=(n:number)=>Math.max(0,Math.min(100,n));
const tokens=(value:string)=>new Set((value||"").toLowerCase().split(/[^a-z0-9]+/).filter(x=>x.length>2));
function topicFit(campaign:Record<string,string>,creator:Record<string,string>){
 const wanted=tokens(`${campaign.target_topics} ${campaign.product_description}`),has=tokens(`${creator.content_topics} ${creator.profile_text} ${creator.category}`);
 const coverage=wanted.size?[...wanted].filter(x=>has.has(x)).length/wanted.size:0;
 const location=!campaign.target_location||creator.location?.toLowerCase().includes(campaign.target_location.toLowerCase())?10:0;
 const language=!campaign.target_language||creator.primary_language===campaign.target_language?5:0;
 return clamp(15+coverage*70+location+language);
}
function buildAnalysis(campaignRows:Record<string,string>[],influencerRows:Record<string,string>[]):Campaign[]{
 const accents=["#6747ee","#ef5da8","#f39b39","#35a982"],fees=influencerRows.map(x=>Number(x.estimated_fee)||0),minFee=Math.min(...fees),maxFee=Math.max(...fees);
 return campaignRows.map((c,index)=>{const ranked=influencerRows.map(x=>{const engagement=Number(x.engagement_rate_pct)||0,growth=Number(x.follower_growth_30d_pct)||0,followers=Number(x.followers)||1,following=Number(x.following)||0;let auth=100;if(following/followers>.02)auth-=20;if(growth>15&&engagement<1.5)auth-=35;if(engagement<.5)auth-=20;const efficiency=maxFee===minFee?70:100-((Number(x.estimated_fee)-minFee)/(maxFee-minFee))*70,fit=topicFit(c,x),eng=clamp(engagement/8*100),score=fit*.5+auth*.25+eng*.15+efficiency*.1;return {handle:x.handle||x.influencer_id,platform:x.platform||"Unknown",category:x.category||"Uncategorised",score,fit,auth:clamp(auth),eng};}).sort((a,b)=>b.score-a.score).slice(0,5);
  const topHandles=new Set(ranked.map(x=>x.handle)),top=influencerRows.filter(x=>topHandles.has(x.handle||x.influencer_id)).slice(0,3),cost=Math.max(1,top.reduce((sum,x)=>sum+(Number(x.estimated_fee)||0),0)),followerBase=top.reduce((sum,x)=>sum+(Number(x.followers)||0),0),aov=Number(c.average_order_value)||1000;
  const makeRoi=(reach:number,ctr:number,conversion:number):Roi=>{const conversions=followerBase*reach*ctr*conversion,revenue=conversions*aov,profit=revenue*.65-cost;return {conversions,revenue,cost,profit,roas:revenue/cost,roi:profit/cost*100}};
  return {id:c.campaign_id||`CAM-${index+1}`,name:c.campaign_name||`Campaign ${index+1}`,objective:c.objective||"Awareness",period:`${c.start_date||"Start"} – ${c.end_date||"End"}`,budget:Number(c.budget)||cost,accent:accents[index%accents.length],compliance:[0,1,0],creators:ranked,roi:{conservative:makeRoi(.28,.02,.03),expected:makeRoi(.35,.025,.04),optimistic:makeRoi(.4025,.03,.05)}};});
}
const icons:Record<string,string>={overview:"M3 3h7v7H3zM14 3h7v4h-7zM14 11h7v10h-7zM3 14h7v7H3z",people:"M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8",shield:"M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10M9 12l2 2 4-4",chart:"M3 20h18M6 16l4-5 4 3 5-8"};
function Icon({name}:{name:string}){return <svg viewBox="0 0 24 24"><path d={icons[name]}/></svg>}

export default function Home(){
 const [campaigns,setCampaigns]=useState(data),[id,setId]=useState("CAM-002"),[scenario,setScenario]=useState("expected"),[notice,setNotice]=useState("Showing synthetic sample data · bundled v1.0"),[complianceResults,setComplianceResults]=useState<ComplianceResult[]>([]),[brief,setBrief]=useState<string[]>([]),[projects,setProjects]=useState<SavedProject[]>([]),[projectsOpen,setProjectsOpen]=useState(false),[projectName,setProjectName]=useState(""),[connectorOpen,setConnectorOpen]=useState(false),[channelId,setChannelId]=useState(""),[youtube,setYoutube]=useState<YouTubeResult|null>(null),[connectorLoading,setConnectorLoading]=useState(false),[connectorError,setConnectorError]=useState("");
 const campaign=useMemo(()=>campaigns.find(x=>x.id===id)??campaigns[0],[campaigns,id]),roi=campaign.roi[scenario],checks=campaign.compliance.reduce((a,b)=>a+b,0);
 async function importReports(files:FileList|null){
  if(!files?.length)return;const next=structuredClone(campaigns);let rankingFiles=0,roiFiles=0;
  for(const file of Array.from(files)){const rows=parseCsv(await file.text());if(!rows.length)continue;
   if("overall_score" in rows[0]&&"handle" in rows[0]){rankingFiles++;for(const base of next){const found=rows.filter(r=>r.campaign_id===base.id).sort((a,b)=>Number(a.rank)-Number(b.rank)).slice(0,5);if(found.length)base.creators=found.map(r=>({handle:r.handle,platform:r.platform||"Unknown",category:r.category||"Unknown",score:Number(r.overall_score)||0,fit:Number(r.campaign_fit_score)||0,auth:Number(r.authenticity_score)||0,eng:Number(r.engagement_quality_score)||0}));}}
   if("scenario" in rows[0]&&"contribution_roi_pct" in rows[0]){roiFiles++;for(const base of next){for(const r of rows.filter(x=>x.campaign_id===base.id)){base.roi[r.scenario]={conversions:Number(r.estimated_conversions)||0,revenue:Number(r.estimated_revenue)||0,cost:Number(r.total_campaign_cost)||0,profit:Number(r.contribution_profit)||0,roas:Number(r.roas_x)||0,roi:Number(r.contribution_roi_pct)||0};}}}
  }
  if(rankingFiles||roiFiles){setCampaigns(next);setNotice(`Session data loaded · ${rankingFiles} ranking file · ${roiFiles} ROI file`);}else setNotice("No compatible report columns found");
 }
 async function analyzeRawData(files:FileList|null){
  if(!files?.length)return;let campaignRows:Record<string,string>[]|null=null,influencerRows:Record<string,string>[]|null=null;
  for(const file of Array.from(files)){const rows=parseCsv(await file.text());if(!rows.length)continue;if("campaign_name" in rows[0]&&"target_topics" in rows[0])campaignRows=rows;if("handle" in rows[0]&&"followers" in rows[0]&&"estimated_fee" in rows[0])influencerRows=rows;}
  if(!campaignRows||!influencerRows){setNotice("Analysis needs both campaigns.csv and influencers.csv");return;}const analyzed=buildAnalysis(campaignRows,influencerRows);if(!analyzed.length){setNotice("No valid campaign rows were found");return;}setCampaigns(analyzed);setId(analyzed[0].id);setScenario("expected");setNotice(`Automated analysis complete · ${influencerRows.length} creators · ${analyzed.length} campaigns`);
 }
 async function checkCaptions(files:FileList|null){
  if(!files?.length)return;let campaignRows:Record<string,string>[]|null=null,submissionRows:Record<string,string>[]|null=null;
  for(const file of Array.from(files)){const rows=parseCsv(await file.text());if(!rows.length)continue;if("campaign_name" in rows[0]&&"required_disclosure" in rows[0])campaignRows=rows;if("submission_id" in rows[0]&&"caption" in rows[0])submissionRows=rows;}
  if(!campaignRows||!submissionRows){setNotice("Caption check needs campaigns.csv and campaign_submissions.csv");return;}
  const results:ComplianceResult[]=submissionRows.map(s=>{const c=campaignRows!.find(x=>x.campaign_id===s.campaign_id),caption=(s.caption||"").toLowerCase();if(!c)return {id:s.submission_id,campaignId:s.campaign_id,score:0,status:"review",missing:["matching campaign"],prohibited:[],suggestion:"Add a matching campaign definition."};
   const required=[...(c.required_hashtags||"").split("|"),...(c.required_mentions||"").split("|"),...(c.required_links||"").split("|"),c.required_disclosure].filter(Boolean),missing=required.filter(x=>!caption.includes(x.toLowerCase())),prohibited=(c.prohibited_terms||"").split("|").filter(x=>x&&caption.includes(x.toLowerCase())),wanted=[...tokens(c.target_topics)],found=wanted.filter(x=>tokens(caption).has(x)),coverage=wanted.length?found.length/wanted.length:1,score=clamp(100-missing.length*15-prohibited.length*30-(1-coverage)*20),status:ComplianceResult["status"]=prohibited.length?"blocked":missing.length||coverage<.6?"review":"compliant";
   const actions=[missing.length?`Add ${missing.join(", ")}`:"",prohibited.length?`Remove ${prohibited.join(", ")}`:"",coverage<.6?`Mention campaign topics: ${wanted.join(", ")}`:""].filter(Boolean);return {id:s.submission_id,campaignId:s.campaign_id,score,status,missing,prohibited,suggestion:actions.join(" · ")||"Ready for human approval."};
  });
  setComplianceResults(results);setCampaigns(current=>current.map(c=>{const own=results.filter(r=>r.campaignId===c.id);return own.length?{...c,compliance:[own.filter(r=>r.status==="compliant").length,own.filter(r=>r.status==="review").length,own.filter(r=>r.status==="blocked").length]}:c;}));
  const selected=campaignRows.find(c=>c.campaign_id===(results[0]?.campaignId||campaignRows![0].campaign_id))||campaignRows[0];setId(selected.campaign_id);setBrief([`Goal: ${selected.objective} for ${selected.product_description}.`,`Cover: ${(selected.target_topics||"").split("|").join(", ")}.`,`Include: ${[selected.required_hashtags,selected.required_mentions,selected.required_links,selected.required_disclosure].filter(Boolean).join(" · ")}.`,`Avoid: ${(selected.prohibited_terms||"No listed terms").split("|").join(", ")}.`,`Success metric: review compliance and campaign outcomes before publishing.`]);setNotice(`Caption audit complete · ${results.length} submissions checked`);
 }
 function exportRankings(){
  const headers=["rank","campaign_id","campaign_name","handle","platform","category","overall_score","campaign_fit_score","authenticity_score","engagement_quality_score"],rows=campaign.creators.map((c,i)=>[i+1,campaign.id,campaign.name,c.handle,c.platform,c.category,c.score.toFixed(2),c.fit.toFixed(2),c.auth.toFixed(2),c.eng.toFixed(2)]),csv=[headers,...rows].map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(",")).join("\n"),url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),link=document.createElement("a");link.href=url;link.download=`${campaign.id.toLowerCase()}-creator-rankings.csv`;link.click();URL.revokeObjectURL(url);setNotice(`Creator rankings exported for ${campaign.name}`);
 }
 function savePdf(){const title=document.title;document.title=`${campaign.name} - InfluencerTrust AI report`;window.print();setTimeout(()=>{document.title=title},500);}
 async function fetchProjects(){const response=await fetch("/api/projects");if(response.status===401){window.location.href="/signin-with-chatgpt?return_to=/";return;}const result=await response.json();setProjects(result.projects||[]);setProjectsOpen(true);}
 async function saveProject(){const name=projectName.trim()||campaign.name,response=await fetch("/api/projects",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,payload:{campaigns,id,scenario,complianceResults,brief}})});if(response.status===401){window.location.href="/signin-with-chatgpt?return_to=/";return;}if(!response.ok){setNotice("Project could not be saved");return;}setProjectName("");setNotice(`Saved project: ${name}`);await fetchProjects();}
 function loadProject(project:SavedProject){setCampaigns(project.payload.campaigns);setId(project.payload.id);setScenario(project.payload.scenario);setComplianceResults(project.payload.complianceResults||[]);setBrief(project.payload.brief||[]);setProjectsOpen(false);setNotice(`Loaded project: ${project.name}`);}
 async function deleteProject(projectId:string){const response=await fetch(`/api/projects?id=${encodeURIComponent(projectId)}`,{method:"DELETE"});if(response.ok)setProjects(current=>current.filter(x=>x.id!==projectId));}
 async function connectYouTube(){setConnectorLoading(true);setConnectorError("");const response=await fetch(`/api/connectors/youtube?channelId=${encodeURIComponent(channelId.trim())}`),result=await response.json();setConnectorLoading(false);if(!response.ok){setConnectorError(result.error||"YouTube could not be connected");return;}setYoutube(result);setConnectorOpen(false);setNotice(`Live YouTube data · ${result.channel.title} · refreshed ${new Date(result.fetchedAt).toLocaleString()}`);}
 return <div className="shell"><aside><div className="brand"><b>IT</b><span>Influencer<em>Trust</em></span></div><nav><a className="active"><Icon name="overview"/>Overview</a><a><Icon name="people"/>Creators</a><a><Icon name="shield"/>Authenticity</a><a><Icon name="chart"/>ROI simulator</a></nav><div className="status"><small>MODEL STATUS</small><strong><i/>Analysis ready</strong><span>Last refreshed today</span></div></aside>
 <main><div className="print-report-header"><b>InfluencerTrust AI</b><h1>{campaign.name}</h1><p>Campaign intelligence report · Generated {new Date().toISOString().slice(0,10)}</p></div><header><div><small>CAMPAIGN INTELLIGENCE</small><h1>Performance overview</h1><p>Rank creators, screen risk and forecast returns in one place.</p></div><div className="header-tools"><button className="connector-button" onClick={()=>setConnectorOpen(true)}>Connect YouTube</button><button className="projects-button" onClick={fetchProjects}>Projects</button><label className="compliance-button">Check captions<input type="file" multiple accept=".csv,text/csv" onChange={e=>checkCaptions(e.target.files)}/></label><label className="raw-button">Analyze raw data<input type="file" multiple accept=".csv,text/csv" onChange={e=>analyzeRawData(e.target.files)}/></label><label className="import-button">Import reports<input type="file" multiple accept=".csv,text/csv" onChange={e=>importReports(e.target.files)}/></label><b>KM</b></div></header>
 <section className="campaign"><div className="current"><i style={{background:campaign.accent}}/><span><small>ACTIVE CAMPAIGN</small><b>{campaign.name}</b></span></div><div className="meta"><span><small>OBJECTIVE</small>{campaign.objective}</span><span><small>RUN DATES</small>{campaign.period}</span><span><small>BUDGET</small>{cash(campaign.budget)}</span></div><select aria-label="Choose campaign" value={id} onChange={e=>setId(e.target.value)}>{campaigns.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></section>
 <div className="data-notice"><span><i/>{notice}</span><button onClick={()=>{setCampaigns(data);setNotice("Showing verified sample data")}}>Reset sample</button></div>
 <div className="report-actions"><span>EXPORT CAMPAIGN REPORT</span><div><button onClick={exportRankings}>Download rankings CSV</button><button className="pdf-button" onClick={savePdf}>Save report as PDF</button></div></div>
 {youtube&&<section className="connector-card"><div><small>VERIFIED API SOURCE</small><h2>{youtube.channel.title}</h2><p>YouTube Data API v3 · {youtube.metrics.sampleSize} recent public videos · refreshed {new Date(youtube.fetchedAt).toLocaleString()}</p></div><span><small>SUBSCRIBERS</small><b>{youtube.channel.subscribers.toLocaleString()}</b></span><span><small>AVG. VIEWS</small><b>{Math.round(youtube.metrics.avgViews).toLocaleString()}</b></span><span><small>VIEW ENGAGEMENT</small><b>{youtube.metrics.engagementRatePct.toFixed(2)}%</b></span></section>}
 <section className="kpis"><Kpi label="Top creator score" value={campaign.creators[0].score.toFixed(1)} note={`@${campaign.creators[0].handle} leads`} badge="Low risk"/><Kpi label="Expected ROI" value={`${campaign.roi.expected.roi.toFixed(1)}%`} note={`${campaign.roi.expected.roas.toFixed(2)}× ROAS`} badge={campaign.roi.expected.roi>=0?"Profitable":"At risk"} bad={campaign.roi.expected.roi<0}/><Kpi label="Compliance health" value={`${Math.round(campaign.compliance[0]/checks*100)}%`} note={`${campaign.compliance[1]+campaign.compliance[2]} item(s) need attention`} badge={`${checks} checks`}/></section>
 <section className="content"><article className="panel ranking"><div className="panel-head"><span><h2>Recommended creators</h2><p>Explainable ranking for campaign fit and quality</p></span><button>View all →</button></div><div className="table"><table><thead><tr><th>RANK</th><th>CREATOR</th><th>OVERALL</th><th>FIT</th><th>AUTHENTICITY</th><th>ENGAGEMENT</th></tr></thead><tbody>{campaign.creators.map((c,i)=><tr key={c.handle}><td><b className={i===0?"rank first":"rank"}>{i+1}</b></td><td><div className="creator"><i>{c.handle.slice(-2)}</i><span><b>@{c.handle}</b><small>{c.platform} · {c.category}</small></span></div></td><td><b>{c.score.toFixed(1)}</b></td><td><Score n={c.fit}/></td><td><Score n={c.auth}/></td><td><Score n={c.eng}/></td></tr>)}</tbody></table></div></article>
 <article className="panel forecast"><div className="panel-head"><span><h2>ROI forecast</h2><p>Scenario-based contribution return</p></span></div><div className="tabs">{["conservative","expected","optimistic"].map(x=><button className={x===scenario?"on":""} onClick={()=>setScenario(x)} key={x}>{x}</button>)}</div><div className="profit"><small>{scenario} contribution</small><strong className={roi.profit<0?"negative":""}>{short(roi.profit)}</strong><em className={roi.roi<0?"negative":""}>{roi.roi>=0?"+":""}{roi.roi.toFixed(1)}% ROI</em></div><div className="bars"><Bar label="Revenue" n={roi.revenue} h={Math.min(100,roi.revenue/33000)}/><Bar label="Cost" n={roi.cost} h={Math.min(100,roi.cost/8000)} kind="cost"/><Bar label="Contribution" n={roi.profit} h={Math.max(12,Math.min(100,Math.abs(roi.profit)/14000))} kind={roi.profit<0?"loss":"gain"}/></div><div className="mini"><span>Conversions<b>{Math.round(roi.conversions)}</b></span><span>ROAS<b>{roi.roas.toFixed(2)}×</b></span></div></article></section>
 {complianceResults.length>0&&<section className="compliance-section"><article className="panel"><div className="panel-head"><span><h2>Caption compliance audit</h2><p>Deterministic evidence with suggested corrections</p></span></div><div className="audit-list">{complianceResults.map(r=><div key={r.id} className="audit-row"><span><b>{r.id}</b><small>{r.campaignId}</small></span><strong>{r.score.toFixed(0)}</strong><em className={r.status}>{r.status}</em><p>{r.suggestion}</p></div>)}</div></article><article className="panel brief"><div className="panel-head"><span><h2>Creator brief</h2><p>Generated from campaign requirements</p></span></div><ol>{brief.map(item=><li key={item}>{item}</li>)}</ol><small>Review with your legal and brand teams before use.</small></article></section>}
 <section className="report-methodology"><h2>Methodology and limitations</h2><div><p><b>Ranking</b>Campaign fit, authenticity, engagement and cost efficiency are combined using documented, explainable weights.</p><p><b>Financial model</b>ROI values are sensitivity scenarios based on reach, click, conversion and contribution-margin assumptions.</p><p><b>Responsible use</b>Results support human decisions. They do not prove fraud, guarantee outcomes, or replace legal and brand review.</p></div></section>
 <footer><span>Scores support decisions; they do not guarantee outcomes.</span><b>InfluencerTrust AI · MVP v1.0</b></footer>
 {projectsOpen&&<div className="modal-backdrop" role="presentation" onMouseDown={()=>setProjectsOpen(false)}><section className="projects-modal" role="dialog" aria-modal="true" aria-labelledby="projects-title" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><span><small>PRIVATE WORKSPACE</small><h2 id="projects-title">Saved projects</h2></span><button aria-label="Close projects" onClick={()=>setProjectsOpen(false)}>×</button></div><div className="save-row"><input aria-label="Project name" value={projectName} onChange={e=>setProjectName(e.target.value)} placeholder={campaign.name}/><button onClick={saveProject}>Save current</button></div><p className="privacy-note">Projects are private to your signed-in ChatGPT account.</p><div className="project-list">{projects.length===0?<p>No saved projects yet.</p>:projects.map(project=><article key={project.id}><button className="project-load" onClick={()=>loadProject(project)}><b>{project.name}</b><small>{project.payload.campaigns.length} campaigns · {new Date(project.updatedAt).toLocaleDateString()}</small></button><button className="project-delete" aria-label={`Delete ${project.name}`} onClick={()=>deleteProject(project.id)}>Delete</button></article>)}</div></section></div>}
 {connectorOpen&&<div className="modal-backdrop" role="presentation" onMouseDown={()=>setConnectorOpen(false)}><section className="projects-modal connector-modal" role="dialog" aria-modal="true" aria-labelledby="connector-title" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><span><small>DATA CONNECTOR</small><h2 id="connector-title">Connect a YouTube channel</h2></span><button aria-label="Close connector" onClick={()=>setConnectorOpen(false)}>×</button></div><p>Enter the channel ID beginning with <b>UC</b>. The server retrieves public channel and recent-video statistics through the official YouTube API.</p><input aria-label="YouTube channel ID" value={channelId} onChange={e=>setChannelId(e.target.value)} placeholder="UCxxxxxxxxxxxxxxxxxxxxxx"/><button onClick={connectYouTube} disabled={connectorLoading}>{connectorLoading?"Connecting…":"Connect channel"}</button>{connectorError&&<p className="connector-error">{connectorError}</p>}<small>API credentials stay server-side and are never sent to your browser.</small></section></div>}
 </main></div>
}
function Kpi({label,value,note,badge,bad=false}:{label:string,value:string,note:string,badge:string,bad?:boolean}){return <article><div><span>{label}</span><em>{badge}</em></div><strong className={bad?"negative":""}>{value}</strong><p>{note}</p><i className="accent"/></article>}
function Score({n}:{n:number}){return <div className="score"><span><i style={{width:`${n}%`}}/></span><small>{n}</small></div>}
function Bar({label,n,h,kind=""}:{label:string,n:number,h:number,kind?:string}){return <div><i className={kind} style={{height:`${h}%`}}/><small>{label}</small><b>{short(n)}</b></div>}
